## FXIME: circleci seems to have issues with running remote docker - turned off currently

version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    working_directory: docker

    steps:
      - checkout

      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: true

      - run: docker build --build-arg USER='user' -t rubuschl/cyclone-v-ide:$(date +%Y%m%d%H%M%S) .
