version: 2
jobs:
  build:
#    docker:
#      - image: ubuntu:18.04

    working_directory: docker

    steps:
      - checkout

      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: true


#      - run:
#          name: Install DOCKER
#          command: 'apt install apt-transport-https ca-certificates curl software-properties-common'
#          command: 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'
#          command: 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"'
#          command: 'apt-get update && apt-get -y install docker-ce docker-ce-cli containerd.io'

#      - run: date

################################################################################
      - run: docker build --build-arg USER='user' -t rubuschl/cyclone-v-ide:$(date +%Y%m%d%H%M%S) .
