version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    steps:
      - checkout

#      - run:
#        name: Greeting
#        command: echo Hello, world.

      - run:
        name: Installing SUDO
        command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'

#      - run:
#        name: Installing GCC
#        command: 'apt-get update && apt-get install -y gcc g++'

#      - run:
#        name: Install CMAKE
#        command: 'apt-get update && sudo apt-get install -y cmake'

#      - run:
#        name: Install NINJA
#        command: 'apt-get update && sudo apt-get install -y ninja'

#      - run:
#        name: Install DOCKER
#        command: 'apt-get update && sudo apt-get install -y docker-ce containerd'

      - run: date

################################################################################
#      -run: cd docker && docker build --build-arg USER='user' -t rubuschl/cyclone-v-ide:$(date +%Y%m%d%H%M%S) .
