version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    working_directory: docker

    steps:
      - checkout

#      - run:
#          name: Greeting
#          command: echo Hello, world.

#      - run:
#          name: Installing SUDO
#          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'

#      - run:
#        name: Installing GCC
#        command: 'apt-get update && apt-get install -y gcc g++'

#      - run:
#        name: Install CMAKE
#        command: 'apt-get update && sudo apt-get install -y cmake'

#      - run:
#        name: Install NINJA
#        command: 'apt-get update && sudo apt-get install -y ninja'

      - setup_remote_docker:
          docker_layer_caching: true

#      - setup_remote_docker:
#          version: 18.06.0-ce

      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

#      - run:
#          name: Install DOCKER
#          command: 'apt install apt-transport-https ca-certificates curl software-properties-common'
#          command: 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'
#          command: 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"'
#          command: 'apt-get update && apt-get -y install docker-ce docker-ce-cli containerd.io'

#      - run: date

################################################################################
      - run: |
          docker build --build-arg USER='user' -t rubuschl/cyclone-v-ide:$(date +%Y%m%d%H%M%S) .
